#ifndef CHORALECD_FEATURES_H
#define CHORALECD_FEATURES_H

#include "config.h"

#define HAVE_LIBOUTPUT HAVE_GSTREAMER
#define HAVE_CD (HAVE_LAME && HAVE_LIBFLAC && HAVE_LIBCDDB && (HAVE_LIBCDIOP || HAVE_PARANOIA))

#endif
