#!/bin/bash

echo "digraph G {"
for j in $* ; do \
    for i in `find $j -maxdepth 2 -name '*.h' -o -name '*.cpp'` ; do
	grep -H '^#include.*".*"' $i \
	    | fgrep -v all- \
	    | fgrep -v ".." \
            | sed -e 's,^,",' -e 's,:," ->,' -e 's,#include,,' -e 's,"\([a-zA-Z][^/]*\)","'$j'/\1",'
    done
done | sort | uniq
echo "}"
