#!/usr/bin/env python2

import sys
import os
import posix
import string

files = sys.stdin.read().split('\n')

scores = []

for f in files:
    if len(f) == 0:
        continue

    ff = open(f, "r")
    lines = ff.read().split('\n')
    yeses = 0;
    noes = 0;
    for line in lines:
        line = line[0:9].strip()
        if line.isdigit():
            yeses+=1
        elif line == "#####":
            noes+=1

    percent =(yeses*100.0/(yeses+noes))
    scores.append((percent,f[:-5]))
    #print f," : ",percent,"%"

scores.sort()

if len(scores) > 0:
    print "The ten least-covered files (not including files with no tests at all):"
    for score in scores[0:10]:
        print "%6.2f%% %s" % score
